### ISSUE TITLE
Illegal kopierter Code! Achtung!

### ISSUE THREAD

**Issue by lennybakkalian** [DavidBlavid/ShufflenetDemo#1]
Hello Sir,

ich bin von der Github Polizei und Sie haben diesen code illegal von [hier ](https://github.com/mindspore-lab/mindcv/blob/b67e31cf4bc644b19c7c5256bfdc74baa4ae7286/mindcv/models/shufflenetv2.py#L137)kopiert!
Geben Sie Credit an den Author oder Sie bekommen eine Anzeige mit einem hohen einstelligen Streitwert von über 3 Dickcoin!

https://github.com/DavidBlavid/ShufflenetDemo/blob/08971610b2160944c6cbe7108962566fbad5a985/architecture/ShuffleNetV2/network.py#L12-L21

**Comment by DavidBlavid** [comment]
Sehr geehrte Github Polizei,

bitte prüfen Sie Zeilen 349 und 350 aus Interface.py, dort finden sie Credit und einen Link zum zugehörigen Github Repository.
https://github.com/DavidBlavid/ShufflenetDemo/blob/08971610b2160944c6cbe7108962566fbad5a985/Interface.py#L349-L350

Sollten Sie trotzdem weiterhin mit legalen Schritten drohen, werde ich mein Anwaltsteam benachrichtigen müssen. Meine Dickcoins sind mir mehr wert als meine Kinder.

Ganz liebe Grüße
David Rath

**Comment by lennybakkalian** [comment]
Sehr geehrter Herr Rath,

ausnahmsweise lass ich Sie mit einem blauen Auge nochmal davon kommen.
Für weitere Fragen wenden Sie sich bitte an meine Werkstudent-Sekretärin @jhKessler _(Gehalt: 14 Dickcoin/Std.)_

Mit freundlichen Grüßen,
Github Polizei
